class OptimizationError(Exception): ...


class ErrorNoVars(OptimizationError): ...


class ErrorNoImprovement(OptimizationError): ...


class ErrorStepLimit(OptimizationError): ...


class ErrorDuringStep(OptimizationError): ...


class ErrorWhileGeneratingSolution(Exception): ...
